### PR TITLE
Fix playlist sync db issue

### LINKED ISSUE #1255: "Synchronisierung aktivieren und Wiedergabelisten übertragen" funktioniert nicht
**Version**
3.23.2

**Describe the bug**
Ich bin in den Einstellungen gerade auf folgende Meldung gestoßen, nachdem unsere Opencastinstanz auf Version 16 geupdatet wurde:

Image
(Gibt es hierzu eigentlich irgendwo eine Beschreibung, welche Vor- oder Nachteile dies hat?)

Nach einem Klick auf den Link passierte erst einmal etliche Sekunden gar nichts und anschließend erschien folgende Fehlermeldung:

Image

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #1255, which enhances playlist migration by enforcing foreign key constraints and make sure the non-nullable columns changes are correctly applied!

PS: the testing environement was a bit confusing for me to make sure that it is working properly, so please test this through!

### CODE REVIEW

**Comment by ferishili** [comment]
The tests are green now!
However, I had to change the foreign key name from `oc_playlist_ibfk_1` to `oc_playlist_ibfk_2` in order for that to work!
This name change would be later confusing from developers because it happens not in migrations but in some files somewhere else!

Please help me make this name change known/notified!

File: lib/Helpers/PlaylistMigration.php [hunk 1]
```diff
@@ -117,7 +117,7 @@ public static function convert()
                 DROP FOREIGN KEY `oc_playlist_ibfk_1`,
                 CHANGE COLUMN `config_id` `config_id` int NOT NULL,
                 CHANGE COLUMN `service_playlist_id` `service_playlist_id` varchar(64) UNIQUE NOT NULL,
-                ADD FOREIGN KEY `oc_playlist_ibfk_1` (`config_id`) REFERENCES `oc_config` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT'
+                ADD FOREIGN KEY `oc_playlist_ibfk_2` (`config_id`) REFERENCES `oc_config` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT'
```
Comment (dennis531) [inline lib/Helpers/PlaylistMigration.php:120]: I think the problem is cause by dropping and add a key with the same name. Do you tested if this problem happens if you add the key in a separate database query?

Comment (ferishili) [reply lib/Helpers/PlaylistMigration.php:120]: I could be!
I did not test it in a separate query!
Let me check!

**Comment by ferishili** [comment]
Separate query worked thanks @dennis531

**Review by dennis531 — APPROVED** [review]
Thanks for the fix! The tests are successful and the code looks good.

**Comment by ferishili** [comment]
Discussion:
- A best practice wiki page is yet to come to cover the fk index etc.
