### PR TITLE
Mark videos unavailable in discovery instead of removing + Opencast API connectivity check in cronjobs

### LINKED ISSUE #1374: Zuordnung der Videos zu Wiedergabelisten nach Störung im Opencasthosting verschwunden
**Version**
3.29

**Describe the bug**
Nachdem unser Opencastsystem heute für etliche Stunden nicht funktionierte (gehostet beim elan e.V., Gründe bitte intern erfragen, wurden uns bislang trotz Meldung nicht mitgeteilt), mussten wir nun feststellen, dass in Stud.IP die Zuordnung der Videos zu den Wiedergabelisten in den Veranstaltungen nicht mehr vorhanden ist. Alle Videos befinden sich nun jeweils in der Standardwiedergabeliste, die anderen sind leer. 
Die Synchronisierung der Wiedergabelisten ist bei uns nicht aktiviert, da nicht möglich, siehe #1255

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #1374,

Main changes in this PR are:
- Introducing cronjob utils namespace which has a trait for oc conecttion
- A new method: `OCConfig::checkOpencastAPIConnectivity`
- All cronjobs now have a connection checker before processing.
- Video is marked unavailable when they are no longer found in OC.

**NOTE:** It would be very helpful to test all cronjobs and verify that everything works as expected!

### CODE REVIEW

File: lib/Helpers/CronjobUtils/OpencastConnectionCheckerTrait.php [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+    protected function isOpencastReachable(int $config_id): bool {
+        $is_opencast_reachable = false;
+        $message = $this->not_reachable_message;
+        try {
+            $is_opencast_reachable = OCConfig::checkOpencastAPIConnectivity($config_id);
+        } catch (\Throwable $th) {
+            $message .= ': ' . $th->getMessage();
+        }
+        if (!$is_opencast_reachable) {
+            echo $message;
```
Comment (dennis531) [inline lib/Helpers/CronjobUtils/OpencastConnectionCheckerTrait.php:33]:
```suggestion
            echo $message . "\n";
```

A new line seems to be missing:
image

**Review by dennis531 — COMMENTED** [review]
Thank you for this fix! 

The new configuration for hiding unavailable videos is working great!

Regarding the server availability check, I am wondering whether this check is sufficient for an OC cluster. For example, the admin node could be available, but not the worker nodes or the presentation node. I am assuming that your implementiation is only checking the admin node.

**Comment by ferishili** [comment]
True, multi-node opencast was not covered, and should be considered of course!

**Review by dennis531 — APPROVED** [review]
